SlarkInc/Controllers/PartialViewController.cs
using System;
using System.Web.Mvc;

namespace SlarkInc.Controllers
{
    public class PartialViewController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
public PartialViewResult ChildAction(DateTime time)
{
    string greetings = string.Empty;
    if(time.Hour > 18)
    {
        greetings = "Good evening. Now is " + time.ToString("HH:mm:ss");
    }
    else if (time.Hour > 12)
    {
        greetings = "Good afternoon. Now is " + time.ToString("HH:mm:ss");
    }
    else
    {
        greetings = "Good morning. Now is " + time.ToString("HH:mm:ss");
    }
    return PartialView("ChildAction",greetings);
}
	}
}

SlarkInc/Views/PartialView/ChildAction.cshtml
@model string
<h2>@Model</h2>

SlarkInc/Views/PartialView/Index.cshtml
@{
    Layout = null;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<h2>Before PartialView</h2>
<hr />
@*@Html.Partial("PartialPage",1)
<hr />
@{
    Html.RenderPartial("PartialPage",2);
}*@
@*@Html.Action("ChildAction", new { time = DateTime.Now })
<hr />
@{
    Html.RenderAction("ChildAction", new { time = DateTime.Now.AddHours(12) });
}*@
<div id="header"></div>
<hr />
<h2>After PartialView</h2>
<script>
    setInterval(LoadAction, 1000);
    function LoadAction()
    {
        var time = new Date();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ChildAction", "PartialView")',
            data: { time: time.getHours() + ":" + time.getMinutes() + ":" + time.getSeconds()},
            datatype: "json",
            success: function (data) {
                $('#header').html(data);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(errorThrown);
            }

        });
    }
</script>